### ISSUE TITLE
Vesper Build failure

### ISSUE THREAD

**Issue by AaronNGray** [graphframework/graphstack#60]
vesper fails to build either with tsc or gulp
```
:\Users\aaron\GitHub\AaronNGray\vesper>gulp
[03:28:31] Requiring external module ts-node/register
ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (C:\Users\aaron\GitHub\AaronNGray\vesper\node_modules\natives\index.js:137:5)
    at Object.req [as require] (C:\Users\aaron\GitHub\AaronNGray\vesper\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\Users\aaron\GitHub\AaronNGray\vesper\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
```

```
C:\Users\aaron\GitHub\AaronNGray\vesper>tsc
../../../AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:78:11
    78 interface IteratorResult<T> { }
                 ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

node_modules/@types/node/index.d.ts:78:11 - error TS2300: Duplicate identifier 'IteratorResult'.

78 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~

  ../../../AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

src/commands/CommandUtils.ts:15:92 - error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?

15         return new Promise((ok, fail) => mkdirp(directory, (err: any) => err ? fail(err) : ok()));
                                                                                              ~~~~

  ../../../AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.promise.d.ts:33:34
    33     new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'value' was not provided.

src/metadata/ActionMetadataBuilder.ts:96:9 - error TS2322: Type 'string | number | symbol' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'.

96         metadata.methodName = action.action;
           ~~~~~~~~~~~~~~~~~~~

src/metadata/ActionMetadataBuilder.ts:97:9 - error TS2322: Type 'string | number | symbol' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'.

97         metadata.name = action.name || action.action;
           ~~~~~~~~~~~~~
Found 5 errors.
```
I have tried latest tsc.

**Comment by AaronNGray** [comment]
Getting the same on the later dependabot/npm_and_yarn%2Ftypeorm-0.2.25 branch too

**Comment by AaronNGray** [comment]
building on **typescript@2.8.1** but not **typescript@latest**
